# Generated by Django 3.0.14 on 2024-11-09 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('novia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novia_couple', to=settings.AUTH_USER_MODEL, unique=True)),
                ('novio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novio_couple', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
