# Generated by Django 5.1.4 on 2025-01-11 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='novia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='novia_couple', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='couple',
            name='novio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='novio_couple', to=settings.AUTH_USER_MODEL),
        ),
    ]
