# Generated by Django 5.1.4 on 2025-01-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoRecuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='recuerdos/')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video')], max_length=10)),
                ('recuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='recuerdos.recuerdo')),
            ],
        ),
    ]
