# Generated by Django 5.1.4 on 2025-01-11 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiovisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('puntuacionM', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('puntuacionF', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('galardonado', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, upload_to='audiovisuals/%Y/%m/%d/')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('audiovisual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='audiovisual.audiovisual')),
                ('genero', models.CharField(choices=[('Acción', 'Accion'), ('Drama', 'Drama'), ('Comedia', 'Comedia'), ('Comedia Romántica', 'Romcom'), ('Ciencia Ficción', 'Ciencia Ficcion'), ('Aventura', 'Aventura'), ('Misterio', 'Misterio'), ('Animación', 'Animacion'), ('Musical', 'Musical'), ('Histórico', 'Historico')], max_length=20)),
                ('cine', models.BooleanField(default=False)),
            ],
            bases=('audiovisual.audiovisual',),
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('audiovisual_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='audiovisual.audiovisual')),
                ('genero', models.CharField(choices=[('Acción', 'Accion'), ('Aventura', 'Aventura'), ('Deporte', 'Deporte'), ('Simulación', 'Simulacion'), ('RPG', 'Rpg'), ('Estrategia', 'Estrategia'), ('Fantasía', 'Fantasia'), ('Carreras', 'Carreras'), ('Puzzle', 'Puzzle'), ('Terror', 'Terror'), ('Musical', 'Musical'), ('Plataformas', 'Plataformas'), ('Shooter', 'Shooter')], max_length=20)),
                ('dificultad', models.CharField(choices=[('Fácil', 'Facil'), ('Medio', 'Medio'), ('Difícil', 'Dificil'), ('Muy Difícil', 'Muy Dificil')], max_length=20)),
                ('horas', models.PositiveIntegerField(default=0)),
            ],
            bases=('audiovisual.audiovisual',),
        ),
    ]
