# Generated by Django 5.1.4 on 2025-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiovisual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiovisual',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
